In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 1.57147654 -0.06816384  1.67863366  0.63225962  1.58239614]


In [3]:
print(a.shape) 
# rank1 array. Does not behave like a row or column vector. Recommended to not use these 

(5,)


In [4]:
print(a.T)

[ 1.57147654 -0.06816384  1.67863366  0.63225962  1.58239614]


In [5]:
print(np.dot(a, a.T))

8.19572553478


In [9]:
# Better practice to commit to make it a column or row vector. (Column vector here)
a = np.random.randn(5,1) 
print(a)

[[-1.56702788]
 [ 0.07613813]
 [-0.59580398]
 [ 1.32920025]
 [-0.80318754]]


In [10]:
print(a.T)

[[-1.56702788  0.07613813 -0.59580398  1.32920025 -0.80318754]]


In [13]:
print(np.dot(a,a.T))

[[ 2.45557639 -0.11931058  0.93364146 -2.08289386  1.25861726]
 [-0.11931058  0.00579702 -0.0453634   0.10120282 -0.0611532 ]
 [ 0.93364146 -0.0453634   0.35498239 -0.79194281  0.47854233]
 [-2.08289386  0.10120282 -0.79194281  1.76677331 -1.06759708]
 [ 1.25861726 -0.0611532   0.47854233 -1.06759708  0.64511022]]


In [17]:
assert(a.shape == (5,1))

In [18]:
# Can always reshape rank1 arrays
a = a.reshape((5,1))